name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Dapatkan Tag Git
      id: git-tag
      run: |
        TAG="latest"
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Debug Git Tag
      run: | 
        echo "Git Tag: $TAG"

    - name: Bangun Docker image
      run: docker build -t redheaven/my-nginx-image:${{ env.TAG }} .

    - name: Masuk ke Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image ke Docker Hub
      run: docker push redheaven/my-nginx-image:${{ env.TAG }}
