name: Docker Build

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Dapatkan Tag Git
      id: git-tag
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
          TAG=$(echo $TAG | sed 's/\//_/')-$(git rev-parse --short $GITHUB_SHA)
        else
          TAG="latest"
          # Tentukan tag versi manual atau gunakan informasi lain dari proyek
          # Contoh menggunakan timestamp sebagai tag versi alternatif
          TAG=$(date "+%Y%m%d%H%M%S")
        fi
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Debug Git Tag
      run: | 
        echo "Git Tag: $TAG"

    - name: Bangun Docker image
      run: docker build -t redheaven/my-nginx-image:${{ env.TAG }} .

    - name: Masuk ke Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image ke Docker Hub
      run: docker push redheaven/my-nginx-image:${{ env.TAG }}
      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.2'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        mkdir -p $HOME/.kube
        mv kubeconfig $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yaml


